# -*- coding: utf-8 -*-
"""ANALISIS_02_ ESPINOSA_ANAYESSICA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UOuruIHsIPSeDoGbhVUFuJ8ufYAPuecB

# PROYECTO 2.

## INTRODUCCIÓN AL ANÁLISIS DE DATOS
"""

import pandas as pd
df = pd.read_csv("synergy_logistics_database.csv")
df["date"] = pd.to_datetime(df["date"])
df['mes'] = df['date'].dt.strftime('%m')
df['anio'] = df['date'].dt.strftime('%Y')
df.head()

df.dtypes

"""## Opción 1) Rutas de importación y exportación.

Synergy logistics está considerando la posibilidad de enfocar sus esfuerzos en las 10 rutas más demandadas. Acorde a los flujos de importación y exportación, ¿cuáles son esas 10 rutas? ¿le conviene implementar esa estrategia? ¿porqué?
"""

def obtienedf(datos): 
  dff = df[df['direction'] == datos]
  dff = dff.groupby(by=['origin','destination'], as_index=False).count()
  dff = dff.filter(['origin','destination','register_id'])
  dff = dff.set_axis(['origen','destino','total'], axis=1)
  dff = dff.sort_values(by='total', ascending=False).head(10)
  dff["Origen_Destino"] = dff["origen"]+"-"+dff["destino"]
  dff = dff.filter(['Origen_Destino','total'])
  return dff

import matplotlib.pyplot as plt
def graficabarras(datos, t):
  df1.plot(kind = 'bar')
  plt.xlabel("Origen - Destino")
  plt.title("Rutas de "+ t )
  plt.ylabel("Viajes")
  plt.xticks(range(10), df1["Origen_Destino"]);

df1 = obtienedf('Exports')
df1

graficabarras(df1,"exportación")

df1 = obtienedf('Imports')
df1

graficabarras(df1, "importación")

"""## Opción 2) Medio de transporte utilizado."""

def medio_transporte(tipo):
  mt = df[df['direction'] == tipo]
  mt = mt.groupby(by=['transport_mode'], as_index=False).count()
  mt = mt.filter(['transport_mode','register_id'])
  mt = mt.set_axis(['transport_mode','total'], axis=1)
  mt = mt.sort_values(by='total', ascending=False).head(10)
  return mt

# Medio de exportación más usado
me = medio_transporte('Exports')
me.head()

# Medio de importación más usado
mi = medio_transporte('Imports')
mi.head()

"""El medio de transporte menos utilizado tanto para importación como para exportación es el aéreo.

## Opción 3) Valor total de importaciones y exportaciones.
"""

def imp_exp(dir,pais):
  ie = df[df['direction'] == dir]
  ie = ie.groupby(by=[pais], as_index=False).count()
  ie = ie.filter([pais,'register_id'])
  ie = ie.set_axis([pais,'total'], axis=1)
  ie = ie.sort_values(by='total', ascending=False)#.head(10)
  suma = ie['total'].sum()
  ie['acumulado'] = ie['total'].cumsum(axis = 0)
  ie['porcentaje'] = (ie['acumulado']/suma)*100
  ie = ie[ie['porcentaje'] < 80]
  return ie

exportaciones = imp_exp('Exports','destination')
exportaciones

importaciones = imp_exp('Imports','origin')
importaciones

"""**A partir del análisis de las opciones anteriores, ¿Cuál opción u opciones es conveniente implementar como base en la estrategia?**
Justifica a la dirección tu recomendación en forma de un reporte respaldado por datos y análisis en una extensión máxima de 1.5 cuartillas.
"""